FROM mcr.microsoft.com/dotnet/sdk:6.0.101-focal AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.csproj .

# copy and publish app and libraries
COPY . .

RUN dotnet restore

COPY fonts/ ../usr/local/share/fonts/

RUN dotnet publish -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/sdk:6.0.101-focal AS base

WORKDIR /app
COPY --from=build /usr/local/share/fonts/ ../usr/local/share/fonts/

RUN apt-get update
RUN apt-get install -y libfontconfig1

# setup ghostscript integration
RUN apt-get install ghostscript=9.50~dfsg-5ubuntu4.6 --yes
ENV GHOSTSCRIPT_PATH=gs

COPY --from=build /app .

ENTRYPOINT ["dotnet", "FrFontSubsetBug.dll"]
